default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  host: localhost

development:
  <<: *default
  database: mystore_development
  
test:
  <<: *default
  database: mystore_test

production:
  <<: *default
  database: mystore_production
  